# docker-compose.yml
version: "3"
services:
  app:
    build: .
    command: sh -c "yarn typeorm:cli migration:run && yarn start"
    depends_on:
      - postgres
    ports:
      - "8888:8888"
      - "5432:5432"
    env_file:
      - env/development.env
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: demopassword
      POSTGRES_USER: demouser
      POSTGRES_DB: demodbname